apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- ../../base
images:
- name: raajpatel229/hackutd-x
  newName: raajpatel229/hackutd-x
  newTag: 280ccb581df1400bd08f8132a5c531bf2baccbd9
