apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- ../../base
images:
- name: raajpatel229/hackutd-x
  newName: raajpatel229/hackutd-x
  newTag: aafbd025ef5d502519c644b2235562ab38ed33ba
